### PR TITLE
SB-749: Implement a raw layout provider

### PR DESCRIPTION
**Pull request by carlspring**
- Initial implementation.
- Minor `*ArtifactManagementService` refactoring.

### CODE REVIEW

**Comment by fuss86** [comment]
> MavenArtifactControllerTest.shouldDownloadProxiedSnapshotArtifactFromGroup:878

The problem is here:

> at org.carlspring.strongbox.controllers.BaseArtifactController.setMediaTypeHeader(BaseArtifactController.java:255)

more precisely:

> RepositoryFileAttributes artifactFileAttributes = Files.readAttributes(artifactPath,RepositoryFileAttributes.class);

this methods throws `java.nio.file.NoSuchFileException` for non existing paths in the file system. In terms of group repositories, artifact paths don't exist.

**Comment by fuss86** [comment]
> MavenArtifactControllerTest.testResolveViaProxyToMavenCentralInGroup:233->resolveArtifact:240 

the same problem

**Comment by fuss86** [comment]
> RawArtifactControllerTest.testDeploy:89->RawRestAssuredBaseTest.assertPathExists:128->RawRestAssuredBaseTest.pathExists:122

There is a casting problem:

> Caused by: java.lang.ClassCastException: org.carlspring.strongbox.io.RepositoryInputStream cannot be cast to org.carlspring.strongbox.io.ArtifactInputStream
	at org.carlspring.strongbox.controllers.raw.RawArtifactController.download(RawArtifactController.java:146)

**Comment by carlspring** [comment]
Merged initial implementation.

**Comment by carlspring** [comment]
@fuss86 , @sbespalov ,

Thanks for helping on this issue!

**Pull request merged**
