### PR TITLE
SB-617: Heavy refactoring of the strongbox-storage-* modules (Phase 2)

### PR DESCRIPTION
**Pull request by carlspring**
SB-617: Heavy refactoring of the strongbox-storage-* modules
------------------------------------------------------------------------
SB-759: Create an implementation for repository features

- Implemented.

SB-760: Implement repository creation strategies per layout provider

- Implemented.

### CODE REVIEW

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@cs-devops-bot rebuild

**Pull request merged**
