### PR TITLE
Issue 1874: Upgrade the org.codehaus.mojo:build-helper-maven-plugin from 1.9.1 to 3.2.0

### PR DESCRIPTION
**Pull request by liooh**
# Pull Request Description

This pull request tests #1874 and is related to strongbox/strongbox-parent#104

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [x] Yes, please see strongbox/strongbox-parent#91
  * [ ] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by liooh** [comment]
Hi @carlspring, any problem for the request to be accepted?

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by liooh** [comment]
I sended the document filled for e-mail carlspring@gmail.com.

**Comment by carlspring** [comment]
Hi,

Thanks for the ICLA! I will have a look tomorrow and get back to you! A prima vista, it looks good!

**Comment by liooh** [comment]
Ok, thanks

**Comment by carlspring** [comment]
Closing this, as the testing was successful (see [here](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1907/2/pipeline)).

**Pull request closed without merging**
