### PR TITLE
Fixed issue #371 Replace the implementation=file-system with data-sto…

### PR DESCRIPTION
**Pull request by dinesh19aug**
…re=file-system + package renaming

### CODE REVIEW

**Comment by carlspring** [comment]
Thank you! Good job!

Could you please also follow the instructions on the [CONTRIBUTING](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page and provide a signed copy of the ICLA?

Other than that the pull looks great!

**Comment by dinesh19aug** [comment]
Signed and sent the ICLA document.

**Comment by carlspring** [comment]
Hi,

I don't think you've sent the ICLA, though, as I haven't received an e-mail
with it...? Am I missing it?

**Comment by carlspring** [comment]
(There's an actual pdf)...

**Comment by dinesh19aug** [comment]
I sent it again, I misspelled the email and it bounced back.

**Comment by carlspring** [comment]
Thank you very much!

**Pull request merged**
