### PR TITLE
Issue-1493 Updated hibernate validator to 6.0.17.Final.

### LINKED ISSUE #1493: Upgrade org.hibernate:hibernate-validator to version 5.2.5.Final, 5.3.6.Final, 5.4.2.Final or higher
# Task Description

Our current version of `hibernate-validator` is prone to arbitrary code execution, as reported [here](https://snyk.io/vuln/SNYK-JAVA-ORGHIBERNATE-451605).

We need to upgrade this in [strongbox-parent](https://github.com/strongbox/strongbox-parent/) to a newer version and validate that things still work. Please, pick the latest version that still works. If none of them are compatible, please apply the necessary changes to fix things.

# Tasks

The following tasks will need to be carried out:
* [ ] Fork the [strongbox-parent](https://github.com/strongbox/strongbox-parent/) and upgrade the version there. If this is a transitive dependency, check where it's coming from and either add an exclusion for it and explicitly override it, or do whatever else needs to be done.
* [ ] Check, if any code changes are required apply any fixes that might be needed.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

### PR DESCRIPTION
**Pull request by PrzemyslawCieslik**
# Pull Request Description
 
This pull request closes #1493 

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.
* [x] Snyk security check passes [check](https://snyk.io//test/github/PrzemyslawCieslik/strongbox-parent?targetFile=pom.xml)

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No
* Does this pull request require other pull requests to be merged first? 
  * [x] Yes, strongbox/strongbox-parent#42 (PR-1503 does not need to be merged)
  * [ ] No
* Does this require an update of the documentation? 
  * [ ] Yes
  * [x] No

### CODE REVIEW

**Comment by fuss86** [comment]
` Files changed 0 ` @PrzemyslawCieslik  ? :)

**Comment by carlspring** [comment]
Most-likely it's because of the version change in the `strongbox-parent`.

**Comment by PrzemyslawCieslik** [comment]
> `Files changed 0` @PrzemyslawCieslik ? :)

Because I change back to original snapshot version @fuss86

**Comment by carlspring** [comment]
Thank you for your fixes! I'm closing this via the parent.

**Pull request closed without merging**
