### PR TITLE
Issue 1873: We need to upgrade the appassembler-maven-plugin from 2.0.0 to 2.1.0

### PR DESCRIPTION
**Pull request by liooh**
# Pull Request Description

This pull request tests #1873 and is related to strongbox/strongbox-parent#108

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [x] Yes, please see strongbox/strongbox-parent#108
  * [ ] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by liooh** [comment]
@carlspring can you help me with that error? The pipelines likes "mvn clean install -Dintegration.tests" seens me ok.

**Comment by carlspring** [comment]
@liooh ,

I have triggered a full build of our pipeline [here](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1918/2/pipeline).

**Comment by liooh** [comment]
Nice, I guess are ok for merge right now :)

**Comment by liooh** [comment]
Hi @carlspring, some problem for accept the PR?

**Comment by carlspring** [comment]
Hi @liooh ,

No, there is no problem, just a long backlog of pull requests (which makes us quite happy, but it just takes some time to get through them)! :)

Thank you for your contribution and congratulations on your first pull request! :)

I will now close this test pull request, as it successfully passes [our testing](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1918/2/pipeline).

**Comment by liooh** [comment]
Ok, thanks @carlspring , I have a question,  isn't it count like hacktoberfest-accepted?

**Comment by carlspring** [comment]
I have added the label, but, since it doesn't get merged, I'm not sure, if this one will count. (Do let me know, if it does, though!).

**Comment by liooh** [comment]
Hi, the PR was counted, thanks @carlspring

**Comment by carlspring** [comment]
Okay, good to know! Thanks! :)

**Comment by carlspring** [comment]
FYI: @steve-todorov .

**Pull request closed without merging**
