### PR TITLE
Issue-950: Make the strongbox-storage-api's tests work in parallel

### LINKED ISSUE #950: Make the strongbox-storage-api's tests work in parallel
The test cases in this module are taking quite a long time, as they're all running consecutively.

With our upgrade of JUnit to JUnit5 (handled by @ptirador in #871), we now have the means to further fine-tune the parallelization of our tests.

* [x] Each test method of each test must now take care of creating its own test resources and not rely on them to be created by a common test initialization method, or other test methods.
* [x] Test cases which require a repository, should create the repository in each test method and not rely on them to be created by a common test initialization method, or other test methods.

This task is a sub-task of #839. For reference of how things should be done, you can have a look at #936.

### PR DESCRIPTION
**Pull request by ptirador**
# Pull Request Description

This pull request closes #950 

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by ptirador** [comment]
@carlspring: This is ready for merging.

**Comment by steve-todorov** [comment]
@ptirador I've just ran a build on this again and it looks like there is a failing test case (`ArtifactEntryServiceTest`). Not sure if this is related to the broken `master` at the moment. Could you please have a look when you have time?

**Comment by ptirador** [comment]
@steve-todorov : I rebased from master, and last 3 Jenkins builds that I ran seemed to be working fine.
The failing test case shouldn't be an issue. 
I could try run a few more builds, if you want.

**Comment by carlspring** [comment]
retry deepcode

**Comment by carlspring** [comment]
anaylyze deepcode

**Comment by carlspring** [comment]
analyze deepcode

**Comment by carlspring** [comment]
Would you mind providing "before and after" build numbers?

**Comment by ptirador** [comment]
@carlspring : The numbers for the execution time, according to the Jenkins log
BEFORE:
`[INFO] Strongbox: Storage [API] ........................... SUCCESS [ 57.890 s]`

AFTER:
`[INFO] Strongbox: Storage [API] ........................... SUCCESS [ 47.549 s]`

**Comment by carlspring** [comment]
Thanks! :)

**Pull request merged**
