### PR TITLE
SB-638: Refactor the strongbox-storage-* modules' structure and introduce new modules, as necessary

### PR DESCRIPTION
**Pull request by carlspring**
Applied required refactoring changes.

### CODE REVIEW

**Comment by carlspring** [comment]
@cs-devops-bot test this please.

**Comment by carlspring** [comment]
@cs-devops-bot test this please.

**Comment by carlspring** [comment]
@cs-devops-bot test this please.

**Comment by steve-todorov** [comment]
@cs-devops-bot test this please.

**Comment by carlspring** [comment]
@cs-devops-bot test this please.

**Comment by steve-todorov** [comment]
@cs-devops-bot test this please.

**Comment by carlspring** [comment]
@cs-devops-bot test this please.

**Comment by steve-todorov** [comment]
@cs-devops-bot test this please.

**Pull request merged**
