### PR TITLE
Issue-947: Make the strongbox-storage-nuget-layout-provider's tests work in parallel.

### LINKED ISSUE #947: Make the strongbox-storage-nuget-layout-provider's tests work in parallel
# Task Description

The test cases in this module are taking quite a long time, as they're all running consecutively.

With our upgrade of JUnit to JUnit5 (handled by @ptirador in #871), we now have the means to further fine-tune the parallelization of our tests.

* [x] Each test method of each test must now take care of creating its own test resources and not rely on them to be created by a common test initialization method, or other test methods.
* [x] Test cases which require a repository, should create the repository in each test method and not rely on them to be created by a common test initialization method, or other test methods.

# Task Links

* This is a sub-task of #839.
* For reference of how things should be done, you can have a look at #936. 
* This task depends on #1083, #1084.

### PR DESCRIPTION
**Pull request by ptirador**
# Pull Request Description

This pull request closes #947 

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by carlspring** [comment]
Awesome! Thank you! :)

**Comment by carlspring** [comment]
Out of curiousity, do you have the before and after numbers for the execution time (just of this module(?

**Comment by ptirador** [comment]
@carlspring : The numbers for the execution time:
BEFORE:
`[INFO] Strongbox: Storage [Nuget Layout Provider] ......... SUCCESS [ 44.377 s]`

AFTER:
`[INFO] Strongbox: Storage [Nuget Layout Provider] ......... SUCCESS [ 25.262 s]`

**Comment by carlspring** [comment]
This is half as much as it used to take! That's fantastic! Thanks!

**Pull request merged**
