### PR TITLE
The directory browsing under /storages should not contain "..", as it points to a non-existing path

### LINKED ISSUE #572: The directory browsing under /storages should not contain "..", as it points to a non-existing path
When browsing `http://localhost:48080/storages/`, there is a link to `..` which is incorrect, as there is nothing above the path that can, or should be browseable.

The code for this is somewhere in the controllers under the `strongbox-web-core` module.

### PR DESCRIPTION
**Pull request by bbb1991**
Fixed #572

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel on Gitter](https://gitter.im/strongbox/strongbox), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by bbb1991** [comment]
@carlspring yeah, sure. I will send ICLA later

**Comment by carlspring** [comment]
Hi @bbb1991,

Have you had a chance to sign the ICLA?

**Comment by bbb1991** [comment]
Hi @carlspring , I've sent signed ICLA to your mail

**Comment by carlspring** [comment]
Thank you for your contribution!

Please join our [Gitter chat](https://gitter.im/strongbox/strongbox), if you'd like to find out how you can help with other tasks as well.

**Pull request merged**
