### PR TITLE
#520 Rename NpmPackageController and NugetPackageController

### LINKED ISSUE #520: Rename the NpmPackageController and NugetPackageController
For consistency, please rename the following artifact controllers:
* `NpmPackageController` to `NpmArtifactController` (for more info, check [NPM Layout Provider](https://github.com/strongbox/strongbox/wiki/NPM-Layout-Provider))
* `NugetPackageController` to `NugetArtifactController` (for more info, check [Nuget Layout Provider](https://github.com/strongbox/strongbox/wiki/NuGet-Layout-Provider))

Also, for consistency, please update the two wiki pages above to point to the renamed classes.

These classes are located under the `strongbox-web-core`.

### PR DESCRIPTION
**Pull request by danielbrzn**
Renamed the package controllers and their relevant tests.

Resolves #520

### CODE REVIEW

**Comment by danielbrzn** [comment]
Hi @carlspring, any idea why the test might be failing? I don't seem to have edited any files that may have caused this test failure.

It appears that there's an extra folder `org` generated inside `\target\strongbox-vault\storages\storage0\releases` which is causing `testRepositoryContents` to fail.

**Comment by carlspring** [comment]
Hi @danielbrzn ,

Thanks for your contribution!

It seems that the following code block in the `BrowseControllerTest` class is at fault:

```
        assertArrayEquals("Returned files", new String[] { "testfile" }, returnedMap.get("files").toArray());
        assertArrayEquals("Returned files", new String[] { "testdir" }, returnedMap.get("directories").toArray());
```

I suggest changing it to something like:

```
        assertTrue("Returned files", returnedMap.get("files").toArray().length > 0);
        assertTrue("Returned files", returnedMap.get("directories").toArray().length > 0);
```

Could you please give this a go and let me know the outcome? Thanks!

Kind regards,

Martin

**Comment by carlspring** [comment]
@guidograzioli ,

Anything other thoughts to add?

**Comment by guidograzioli** [comment]
Not really; I was expecting the web-core component to come up clean for testing, I'll need to change the test in BrowseController by adding some sanity/mocking instead. (no idea where the org directory comes from anyway).

**Comment by carlspring** [comment]
@guidograzioli : The problems in that test that I fixed earlier this week were related to exact expectations on things that are actually quite likely to change with the addition of new code. (If you have a look at the version history of that test, you'll see what I mean). Do you see anything else obvious in the test apart from what I pointed that could be an issue here?

**Comment by guidograzioli** [comment]
@carlspring ok; I'd suggest to set the test method as ignored instead of relaxing the assertion thought. I'll try to come up with something more reliable tomorrow for that test class.

**Comment by carlspring** [comment]
Okay, great!  Thanks a lot!

**Comment by carlspring** [comment]
Thanks!

**Pull request merged**
