### PR TITLE
Issue 1170: Drop Role#repository field

### LINKED ISSUE #1170: Drop Role#repository field
# Task Description

We should drop the `repository` field from the following classes:

* `org.carlspring.strongbox.authorization.domain.Role`
* `org.carlspring.strongbox.authorization.dto.RoleDto`
* `org.carlspring.strongbox.forms.RoleForm`

This field is currently unused and demands unnecessary attention from the developers.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by prbobba**
Fixes #1170.

Build is successful with both the commands 
```
mvn clean install
```
and
```
mvn clean install -Dintegration.tests
```

### CODE REVIEW

**Comment by carlspring** [comment]
Thanks, @prbobba !

@fuss86 , could you please review this?

**Comment by fuss86** [comment]
LGTM :) Please rebase onto master @prbobba :)

**Comment by carlspring** [comment]
Thanks for reviewing, @fuss86 , and thanks for your contribution, @prbobba ! :)

I will merge it as soon as you've rebased.

**Comment by carlspring** [comment]
@prbobba : Could you please rebase, so that we could merge this? :)

**Comment by prbobba** [comment]
how do I properly rebase? I am new to this.

**Comment by fuss86** [comment]
Try this https://strongbox.github.io/developer-guide/git/rebase-vs-merge.html

**Comment by fuss86** [comment]
Hi @prbobba, do you need some help rebasing it ?

**Comment by prbobba** [comment]
image
I am trying the steps at -- https://strongbox.github.io/developer-guide/git/rebase-vs-merge.html
But facing the above issue.

**Comment by prbobba** [comment]
Never mind, its the problem with my ssh public key. regenerated a new one and it works fine :)

**Pull request merged**
