### PR TITLE
Issue 1165: Migrate the MavenRepositoryManagementServiceImplTest and ArtifactMetadataServiceReleasesTest tests to use the new annotations

### PR DESCRIPTION
**Pull request by yugander-krishan-singh**
Added `@TestRepository` and `@TestArtifact` annotations in test classes `MavenRepositoryManagementServiceImplTest.java` and `ArtifactMetadataServiceReleasesTest.java`

Fixes for #1165.

### CODE REVIEW

**Comment by carlspring** [comment]
@yugander-krishan-singh : Thanks for these fixes!

Could you please also do it for `MavenRepositoryManagementServiceImplTest.testCreateAndDelete`, or would it not work...?

**Comment by yugander-krishan-singh** [comment]
> @yugander-krishan-singh : Thanks for these fixes!
> 
> Could you please also do it for `MavenRepositoryManagementServiceImplTest.testCreateAndDelete`, or would it not work...?

@carlspring I tried for `MavenRepositoryManagementServiceImplTest.testCreateAndDelete` but then I am getting the following error-
`org.springframework.context.ApplicationContextException: Failed to close context.; nested exception is java.io.IOException: Failed to close following repositories: [rmsi-releases-1]`

The reason is that @TestRepository annotation creates the repo in the beginning and then deletes it once the test method execution ends.

Now in `testCreateAndDelete` method the repository is deleted before the method ends -
```
closeIndexer(STORAGE0 + ":" + REPOSITORY_RELEASES_2 + ":" + IndexTypeEnum.LOCAL.getType());

        getRepositoryManagementService().removeRepository(STORAGE0, REPOSITORY_RELEASES_2);

        assertFalse(repositoryDir.exists(), "Failed to remove the repository!");
```
Now when the method execution ends due to @TestRepository annotation it agains tries to delete the same repo but since it has already been deleted it throws the error mentioned above.

I can use the annotation but then I need to create the repository once it is deleted and asserted so that @TestRepository finds the repo and deletes it. I have tried it and it works. But then I didn't see any point in doing so.
IMHO since the method is named createAndDelete as it tests creation and deletion of repository, we should not use annotation and let the existing behavior be.
Kindly let me know your thoughts.

**Comment by yugander-krishan-singh** [comment]
> @yugander-krishan-singh : Thanks for these fixes!
> 
> Could you please also do it for `MavenRepositoryManagementServiceImplTest.testCreateAndDelete`, or would it not work...?

@carlspring I have made the changes. Pls check.

**Comment by carlspring** [comment]
Thanks for looking into this, @yugander-krishan-singh! :)

**Pull request merged**
