### PR TITLE
Fixing RawArtifactControllerTestIT failure due to slackbuild.org outage

### LINKED ISSUE #1801: Fix failing test RawArtifactControllerTestIT
# Task Description
All the tests of `RawArtifactControllerTestIT` because `http://slackbuilds.org ` is not working.
Test uses above url to download raw file.

# Tasks

The following tasks will need to be carried out:
* [x] Change `REMOTE_URL` from `http://slackbuilds.org` to  `https://github.com/`
* [x] Change value `testResolveArtifact.pathStr` to any github file.

# Useful Links

* [Failing build](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1799/5/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

### PR DESCRIPTION
**Pull request by anki2189**
# Pull Request Description

This pull request closes #1801 

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by anki2189** [comment]
@carlspring , @steve-todorov Please review the changes.

**Comment by anki2189** [comment]
> LGTM! Thanks! :)

Thanks @carlspring . Can we merge this now?

**Comment by carlspring** [comment]
@anki2189 ,

Yes, we can. We had some problems with our test infrastructure this week, but things are now back to normal.

**Comment by carlspring** [comment]
@anki2189 ,

I'm afraid there are some test failures in the `s-w-i-t` in build [#3](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1804/3/pipeline/198). Would you mind having a look at them?

**Comment by anki2189** [comment]
> @anki2189 ,
> 
> I'm afraid there are some test failures in the `s-w-i-t` in build [#3](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1804/3/pipeline/198). Would you mind having a look at them?

@carlspring `s-w-i-t` test are failing with reason `FileSystemStorageProvider` cannot be resolved. I believe it was related to  `FileSystemStorageProvider` refactoring . Can you please re-trigger another build for this PR.

**Comment by anki2189** [comment]
@carlspring rebased it with master, `s-w-i-t` tests are passing now.

**Comment by carlspring** [comment]
Excellent, thank you! :)

**Pull request merged**
