### PR TITLE
SB-1404 UserDto.lastUpdate never updated - fix

### PR DESCRIPTION
**Pull request by fuss86**

### CODE REVIEW

**Comment by fuss86** [comment]
Deploy result: `3min 19s` compared to master: `6min 49s`

https://jenkins.carlspring.org/job/strongbox/job/builds/job/strongbox-against-strongbox-from-sources/

**Comment by carlspring** [comment]
Looks good to me, thanks! :)

**Comment by steve-todorov** [comment]
Numbers look very good to me! Thanks for all the debugging and digging into the issue! :)

// FYI: The mentioned times is for the entire stage which attempts do two deployments.

**Comment by sbespalov** [comment]
LGTM, thanks @fuss86 :+1:

**Pull request merged**
