### PR TITLE
Issue 1257: Minor refactoring of the strongbox-data-service module

### LINKED ISSUE #1257: Minor refactoring of the strongbox-data-service module
# Task Description

We need a minor refactoring of the `strongbox-data-service` module.

# Tasks

The following tasks will need to be carried out:
* OrientDB configuration-related refactoring:
  * [ ] Create package called `org.carlspring.strongbox.config.orientdb`.
  * [ ] Move `InMemoryOrientDbConfig` under `org.carlspring.strongbox.config.orientdb`.
  * [ ] Move `EmbeddedOrientDbConfig` under `org.carlspring.strongbox.config.orientdb`.
  * [ ] Move `CommonOrientDbConfig` under `org.carlspring.strongbox.config.orientdb`.
  * [ ] Rename `OrientDBProfile` to `OrientDbProfile` and move it under `org.carlspring.strongbox.config.orientdb`.
* Hazelcast configuration-related refactoring:
  * [ ] Create package called `org.carlspring.strongbox.config.hazelcast`.
  * [ ] Move `HazelcastConfiguration` under `org.carlspring.strongbox.config.hazelcast`.
  * [ ] Move `HazelcastInstanceId` under `org.carlspring.strongbox.config.hazelcast`.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by Rathan-Naik**
Fixes #1257.

Minor refactoring of the strongbox-data-service module

OrientDB configuration-related refactoring:
- [x]  Create package called `org.carlspring.strongbox.config.orientdb`.
- [x]  Move `InMemoryOrientDbConfig` under `org.carlspring.strongbox.config.orientdb`.
- [x]  Move `EmbeddedOrientDbConfig` under `org.carlspring.strongbox.config.orientdb`.
- [x]  Move `CommonOrientDbConfig` under `org.carlspring.strongbox.config.orientdb`.
- [x]  Rename `OrientDBProfile` to `OrientDbProfile` and move it under `org.carlspring.strongbox.config.orientdb`.

Hazelcast configuration-related refactoring:
- [x]  Create package called `org.carlspring.strongbox.config.hazelcast`.
- [x]  Move `HazelcastConfiguration` under `org.carlspring.strongbox.config.hazelcast`.
- [x]  Move `HazelcastInstanceId` under `org.carlspring.strongbox.config.hazelcast`.

Acceptance Test
- [x]  Building the code with `mvn clean install -Dintegration.tests` still works.
- [x]  Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
- [x]  Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
- [x] The tests in the `strongbox-web-integration-tests` still run properly.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Kind regards,

Martin

**Comment by steve-todorov** [comment]
@carlspring build is passing, ignore failing smoke test (it's related to #1251).

**Comment by carlspring** [comment]
@steve-todorov : Thanks for clarifying! :)

**Comment by carlspring** [comment]
@Rathan-Naik ,

Have you had a chance to look into the ICLA? :)

**Comment by Rathan-Naik** [comment]
@carlspring Just signed and sent by mail.
Thanks

**Comment by carlspring** [comment]
Thanks for your help and congratulations on your first pull request! :)

**Comment by Rathan-Naik** [comment]
Thank you.
Looking forward to making more contributions.

**Pull request merged**
