### PR TITLE
Issue-1001: CronTaskController is unable to return list of tasks. [NEW]

### LINKED ISSUE #1001: CronTaskController is unable to return list of tasks
The `CronTaskController#getConfigurations` is unable to return the list of cron tasks - it returns `406 Could not find acceptable representation`. This is likely because of broken serialization to JSON. We need to create a test case which checks if the endpoint actually returns a valid response with at least one result inside. 

NOTE: The returned crontasks JSON should look like this:

```
{
   "crontasks": [
      {uuid: ...., name: ....., etc },
      {uuid: ...., name: ....., etc },
      ......
   ]
}
```

### PR DESCRIPTION
**Pull request by ptirador**
Fixes #1001.

This replaces the previous PR #1004.

### CODE REVIEW

**Comment by ptirador** [comment]
@carlspring @steve-todorov Please, could you have a look? Thanks!

**Comment by steve-todorov** [comment]
Hi Pablo, 

Thanks for the rebase! It looks like there is something wrong when running `mvn clean install -DskipTests ; cd strongbox-web-core ; mvn clean spring-boot:run`. Could you please have a look? 

// Interestingly the tests are passing! :D

**Comment by ptirador** [comment]
Hi @steve-todorov, this seems to be happening in the current `master` branch. Can it be related to #1020 PR?

**Comment by steve-todorov** [comment]
@carlspring *cough*, *cough*... it looks like you did an "oops"? :D

**Comment by carlspring** [comment]
Hm... my apologies! I will have a look as soon as I can!

**Comment by steve-todorov** [comment]
Thanks for your work on this Pablo! It works fine for me :)

Note: We should remove `**security/snyk - strongbox-cron/strongbox-cron-rest/pom.xml (strongbox) **` from `snyk` after merging this as it will be no longer available.

**Comment by carlspring** [comment]
Thanks, you guys! :)

**Pull request merged**
