### PR TITLE
Issue 1167:  Replace application.properties by yaml equivalent

### LINKED ISSUE #1167: Replace application.properties by yaml equivalent
# Task Description

See also https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml

# Acceptance Test

* [ ] Building the code and running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Task Relationships

This task is a follow-up of #965 (#1056).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by sudhs22**
Fixes #1167.

- Replaced `application.properties` with `application.yaml`.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi, @sudhs22!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

I have updated your PR's decription to also include the acceptance tests for this task. Could you please confirm, if all these tests pass as well? Thanks!

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by sudhs22** [comment]
Hey Martin,

I will sign the ICLA and send the scan copy on this email in 2 days time.
I have run the command "mvn clean install", which ran all the tests and it
passed. Let me know if anything other tests needs to be run.

Thanks a lot.

Regards,
Sudeep

**Comment by carlspring** [comment]
Hi,

We'll need to have your ICLA before being able to merge this PR.

In your comment above, I have listed the things you will need to run in order to check, if your changes work properly across all the affected projects and modules. Could you please look into this?

**Comment by carlspring** [comment]
Heey @sudhs22 ,

Have you had a chance to sign the ICLA?

**Comment by carlspring** [comment]
Hey @sudhs22 ,

Have you had a chance to sign the ICLA? We'll need you to sign this in order to be able to accept and merge your pull requests.

**Comment by ptirador** [comment]
Hi @carlspring, in case @sudhs22 doesn't answer, I can take it (Wold I have to create another PR?

**Comment by carlspring** [comment]
@ptirador : Please, proceed! ;)

**Comment by carlspring** [comment]
Thanks for your efforts, @sudhs22, but we can only merge pull requests from contributors who have signed the ICLA.

Closed in favour of #1283.

**Pull request closed without merging**
