### PR TITLE
Upgrade the org.codehaus.mojo:build-helper-maven-plugin from 1.9.1 to 3.2.0 #1874

### PR DESCRIPTION
**Pull request by mknutsen79**
# Pull Request Description

This pull request relates to #1874

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [ ] No

* Does this pull request require other pull requests to be merged first? 
  * [x] Yes, please see strongbox/strongbox-parent#96
  * [ ] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by carlspring** [comment]
@mknutsen79 ,

This pull request contains no changes. Should it be closed, or did you mean to make any changes?

**Comment by mknutsen79** [comment]
The change that was made was reverting the pom versions back to 1.0-SNAPSHOT instead of being the 1.0-issue-1874-SNAPSHOT like it says to do in the last step of the directions on updating dependencies.

**Comment by carlspring** [comment]
> The change that was made was reverting the pom versions back to 1.0-SNAPSHOT instead of being the 1.0-issue-1874-SNAPSHOT like it says to do in the last step of the directions on updating dependencies.

That particular last step is done by us, the core team, after we've checked that things pass in our CI server. You you might want to re-do this pull request and not do that. :)

**Comment by mknutsen79** [comment]
Ah alright, will do!

**Comment by carlspring** [comment]
Closing this as a duplicate of #1907 .

**Pull request closed without merging**
