### PR TITLE
Issue #406 Updated quartz-scheduler to v.2.3.0

### PR DESCRIPTION
**Pull request by sanket407**
Passed all the CRON tests .

### CODE REVIEW

**Comment by carlspring** [comment]
Excellent!

Could you please sign the lCLA, as described in the [Contributing.md](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page and mail me the signed document?

**Comment by sanket407** [comment]
@carlspring I have mailed it to you yesterday . Please check

**Comment by carlspring** [comment]
Are you referring to the signed PDF? If so, then I'm afraid I haven't
received it. Would you mind sending it again to
martin.todorov@carlspring.com?

On 10 Dec 2017 14:59, "sanket407" <notifications@github.com> wrote:

@carlspring <https://github.com/carlspring> I have mailed it to you
yesterday . Please check

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/strongbox/strongbox/pull/413#issuecomment-350550304>,
or mute the thread

**Comment by sanket407** [comment]
Had branching issues ! Making new pull request !

**Comment by carlspring** [comment]
Did you close this by accident? I still haven't merged it. (I was waiting for the ICLA).

**Comment by carlspring** [comment]
Ah, okay!

**Pull request closed without merging**
