### PR TITLE
Apply one separate repository for each test

### PR DESCRIPTION
**Pull request by mslowiak**
# Pull Request Description

This pull request reference to #1389.
It is another fix connected with #1470.
 
Fixes:

> Failed to lock [storage0/xxxxx] after [8] seconds. Consider to use unique resource ID for your test."

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [x] Yes
  * [ ] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by mslowiak** [comment]
Build blocked by #1479

**Comment by carlspring** [comment]
@mslowiak : Would you like to look into the SBT test issue?

**Comment by mslowiak** [comment]
@carlspring yup, I can look on it

**Comment by carlspring** [comment]
image

**Pull request merged**
