### PR TITLE
Issue-1304: Create a NugetTestArtifact annotation.

### LINKED ISSUE #1304: Create a NugetTestArtifact annotation
# Task Description

As part of our on-going efforts to re-work our tests, so that they're simpler and easier to parallelize an in continuation of our recent work on getting test annotations for the easier generation of test repositories and artifacts, we need to implement an NuGet-specific annotation for test artifacts. Please, refer to the [documentation](https://strongbox.github.io/developer-guide/writing-tests.html) for more details on how this is implemented. At the moment, we only have these annotations for Maven.

# Tasks

* [ ] Implement an `NugetTestArtifact` annotation.
* [ ] Update the [documentation](https://strongbox.github.io/developer-guide/writing-tests.html).

# Task Relationships

This task:
* Relates to: #1294 , #1165, #1198 , #1219 , #1303 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by ptirador**
Fixes #1304.

# Tasks
* [x] Create [Pull Request](https://github.com/strongbox/strongbox-web-integration-tests/pull/51) for `s-w-i-t`.

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

### CODE REVIEW

**Comment by carlspring** [comment]
@ptirador : The tests still seem to be failing despite me merging the PR for the `s-w-i-t`. Would you mind taking another look? Thanks! :)

**Comment by ptirador** [comment]
Everything works fine in my local environment...
@steve-todorov: could you see if this Jenkins build is pointing to strongbox/strongbox-web-integration-tests#51?

**Comment by steve-todorov** [comment]
@carlspring you were running this PR against the strongbox/strongbox-web-integration-tests#master, instead of strongbox/strongbox-web-integration-tests#51, which is why this was failing. 

After rerunning the build with the proper parameters it's all green. :)

**Comment by carlspring** [comment]
Interesting! I thought I'd merged that to the `master` already?

**Comment by carlspring** [comment]
Hi @ptirador ,

Could you please reabse your branch? Thanks!

**Comment by ptirador** [comment]
> Hi @ptirador ,
> 
> Could you please reabse your branch? Thanks!

@carlspring : Rebase done!

**Comment by carlspring** [comment]
Thanks, Pablo! :)

**Pull request merged**
