### PR TITLE
Issue 1853: Upgrade our hamcrest dependencies from 1.3 to 2.2

### LINKED ISSUE #1853: Upgrade our hamcrest dependencies from 1.3 to 2.2
# Task Description

We need to upgrade our `hamcrest` dependencies from `1.3` to `2.2`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to: #1852 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

### PR DESCRIPTION
**Pull request by ptirador**
# Pull Request Description

This pull request closes #1853 

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [x] Yes, please see strongbox/strongbox-parent/pull/87
  * [ ] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Review by steve-todorov — APPROVED** [review]
LGTM and all tests are [passing](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1890/4/pipeline/)! You can revert the versions back to `1.0-SNAPSHOT` and I'll merge :) 

Thanks for fixing this Pablo!

**Comment by carlspring** [comment]
Closing this as the [Jenkins tests were successful](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1890/4/pipeline).

**Comment by steve-todorov** [comment]
There's a change in `strongbox-web-core/pom.xml` related to the `<artifactId>hamcrest</artifactId>` :)

**Comment by ptirador** [comment]
@steve-todorov: version reverted and Jenkins build is passing. You can merge :)

**Comment by steve-todorov** [comment]
Thanks for your work @ptirador ! :)

**Pull request merged**
