### PR TITLE
Issue-931: MavenArtifactControllerTest proper cleanup

### LINKED ISSUE #931: MavenArtifactControllerTest proper cleanup
We need to properly cleanup test resources left. 

PR example: https://github.com/strongbox/strongbox/pull/920/files

See also
- `@AfterEach`
- `removeRepositories();`
- `removeRepositories(getRepositoriesToClean());`
along the codebase.

Required for #927

### PR DESCRIPTION
**Pull request by ptirador**
Fixes #931.

@fuss86, even with these changes, if i re-enable the failing test in #927, this one keeps failing. What could be left?

### CODE REVIEW

**Comment by fuss86** [comment]
But [Jenkins build](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fstrongbox/detail/PR-932/1/pipeline) is green here, no `AqlControllerTest` issues here.

Please paste the failure reason.

**Comment by ptirador** [comment]
No, that test is still `@Disabled`, but I removed this annotation when I was testing in my local environment and the error was the same.

**Comment by ptirador** [comment]
@fuss86: Forget about what I said earlier. I've just reenabled the failing test, and everything's working fine.
So, this fixes #931 and #927.

**Comment by fuss86** [comment]
@carlspring, you can then merge it :)

**Comment by carlspring** [comment]
Thanks for confirming!

**Pull request merged**
