### PR TITLE
Issue-1062: Make the *ArtifactControllerTests not print the contents of artifacts to the console

### LINKED ISSUE #1062: Make the *ArtifactControllerTests not print the contents of artifacts to the console
# Task Description

The `*ArtifactControllerTest`-s are printing out the contents of artifacts to the console. This causes:
- Windows consoles to break
- IntelliJ terminals (under Windows) to break
- An awful lot of unnecessary and human-unintelligible output in the console

We need to silence this output when the tests below are executed.

Affected tests:
- [ ] `MavenArtifactControllerTest`
- [ ] `NpmArtifactControllerTest`
- [ ] `NugetArtifactControllerTest`
- [ ] `RawArtifactControllerTest`

The problem here may lie in the restassured dependency. Maybe we could upgrade to a newer version of it (the latest currently being `3.3.0`) and perhaps we can control it somehow through there. This needs to be investigated and fixed. We might have to create a fix for the restassured project itself and contribute it back to them.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by mujahid**
fixes #1062 
- Fixed MavenArtifactControllerTest to avoid printing the contents artifacts
- Fixed NpmArtifactControllerTest to avoid printing the contents artifacts

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Kind regards,

Martin

**Comment by mujahid** [comment]
> Hi!
> 
> Thank you for your contribution!
> 
> Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?
> 
> Kind regards,
> 
> Martin

Email sent

**Comment by carlspring** [comment]
Thanks!

One more thing -- could you please add yourself to the table in the `CONTRIBUTING.md` page? Thanks! :)

**Comment by carlspring** [comment]
I can confirm that this fixes the issue completely! Thanks again and congratulations on your first pull request! :)

**Pull request merged**
