### PR TITLE
Renaming NullArtifactCoordinates,NullArtifactGenerator,NullRepository

### PR DESCRIPTION
**Pull request by anki2189**
#1587 
#1582

### CODE REVIEW

**Comment by anki2189** [comment]
@wpater Please rebase your branch once this PR is accepted.

**Comment by anki2189** [comment]
@carlspring Pls accept this PR.

**Comment by wpater** [comment]
> @wpater Please rebase your branch once this PR is accepted.

Conflicts incoming :)

**Comment by anki2189** [comment]
> > @wpater Please rebase your branch once this PR is accepted.
> 
> Conflicts incoming :)

**Comment by anki2189** [comment]
> > @wpater Please rebase your branch once this PR is accepted.
> 
> Conflicts incoming :)

:)

**Pull request closed without merging**
