### PR TITLE
Issue 1862: Check build with parent version to 1.0-issue-1862-SNAPSHOT using commons-collections4:4.4

### LINKED ISSUE #1862: Upgrade from commons-collections:commons-collections:3.2.2 to org.apache.commons:commons-collections4:4.4
# Task Description

We need to upgrade `commons-collections:commons-collections:3.2.2` to `org.apache.commons:commons-collections4:4.4`. Please, note that this will probably require code changes as well.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to:  #1847 , #1859 , #1860, #1861 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

### PR DESCRIPTION
**Pull request by flaix**
# Pull Request Description

This pull request closes #1862

It supersedes PR #1903

This pull requests tests PR strongbox/strongbox-parent#116, superseding strongbox/strongbox-parent#102.

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

# Code Review And Pre-Merge Checklist

* [x] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code in hard-to-understand areas.
* [x] My changes generate no new warnings.
* [ ] I have added tests that prove my fix is effective or that my feature works.
* [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by flaix** [comment]
Is this expected that the web integration and smoke tests are skipped, or was it something else that I did or didn't?

**Comment by carlspring** [comment]
They had passed earlier when I (manually) triggered the complete build pipeline. We trigger this manually, because it's running on our own infrastructure and it takes ~30 minutes to test absolutely everything with many tests running in parallel containers. When I asked you to revert the snapshot version, part of the build was re-triggered, which is what the Github checks changed. They do work, it's just that the "successful" state got wiped out. Also, we're going to ditch the Travis MacOS build as it's an disappointment that almost always times out, because it's simply Travis being Travis. We have already implemented a Github Action for MacOS builds, but we'll roll it out further down the line.

**Comment by carlspring** [comment]
Testing in [Jenkins](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/branches/)...

**Comment by carlspring** [comment]
Tested successfully, closing.

**Comment by carlspring** [comment]
Thanks for your help! :)

**Pull request closed without merging**
