### PR TITLE
Make sure ArtifactCoordinateValidatorsManagementController is following the How-To-Write-Controllers guide

### PR DESCRIPTION
**Pull request by ptirador**
Related issue: #609 

Methods modified in `RepositoryVersionValidatorsManagementController` to follow the [controllers guide](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers).

The proper tests cases have been modified and new cases have been added.

### CODE REVIEW

**Comment by steve-todorov** [comment]
@ptirador this seems to be working just fine. Good job! Could you please rebase? It appears that @carlspring's latest merge has renamed this class into [ArtifactCoordinateValidatorsManagementController](https://github.com/strongbox/strongbox/pull/617/files#diff-b0071e8196a360cc1a9247fde1e5e981)

**Comment by ptirador** [comment]
@steve-todorov I just did the rebase. Could you take a look at the Jenkins build? I'm not sure what's going on.

**Comment by steve-todorov** [comment]
@ptirador I've triggered a rebuild and it's passing in Jenkins now. However, it seems like you still have conflicts you need to resolve?

**Comment by ptirador** [comment]
@steve-todorov Conflicts fixed.

**Comment by steve-todorov** [comment]
@ptirador Great, thanks for your work! 

@carlspring we can merge this now :)

**Comment by carlspring** [comment]
@ptirador,

In the future, could you please rebase instead of merge? Reviewing the PR as it is will take forever like this. The `diff` is truly massive.

**Comment by carlspring** [comment]
Other than my request, about using rebasing vs merging, things look great, thanks! :)

**Pull request merged**
