### PR TITLE
Added validation for OPTIONS request on entryPoint

### LINKED ISSUE #1235: Should not return www-authenticate request method is OPTIONS
# Task Description

This used to work, but for some reason it's broken now (not sure if it's a newer Chrome version or we just broke it somehow). 
In general, when a browser is trying to access an `api` endpoint, it would first send an `OPTIONS` request to check the `CORS` settings of the server and then send the actual request. The first request will **not** contain the `X-Requested-With` header (#457) so that's what's causing the native `HttpBasic` browser popup to appear.  

Steps to reproduce:
1. Set a small session timeout (i.e. 2-3 seconds)
2. Login
3. Wait a few seconds
4. Refresh page

```
# curl -I 'http://localhost:48080/api/ping/token' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost:48080/' -H 'DNT: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36' -H 'Authorization: Bearer INSERT_A_REAL_TOKEN' -X OPTIONS --compressed

HTTP/2 401 
server: nginx
date: Tue, 18 Sep 2018 21:29:14 GMT
content-type: application/json
www-authenticate: Basic realm="Strongbox Repository Manager"
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
```

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Task Relationships

This task relates to #457.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov 
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by AlekNiebla**
Fixes #1235.

I just added a validation inside the Http401AuthenticationEntryPoint.java along the one that it had before.

With this is checks if a request has the desired Authentication header and that its not an OPTIONS request.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi, @AlekNiebla,

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by AlekNiebla** [comment]
okay, I'll be sending the ICLA later today.

**Comment by carlspring** [comment]
Thanks! I'll be looking forward to your signed ICLA, as we can merge pull requests without this.

**Comment by carlspring** [comment]
Thanks for your help and congratulations on your first pull request!

**Pull request merged**
