### PR TITLE
SB-1204: OEntityUnproxyAspect removed [in-progress]

### PR DESCRIPTION
**Pull request by sbespalov**

### CODE REVIEW

**Comment by carlspring** [comment]
@sbespalov ,

What is the status of this task? Is it still required, or should we close it?

**Comment by sbespalov** [comment]
@carlspring we still need to do it someday

**Comment by carlspring** [comment]
@sbespalov : 

With the on-going work on the Janusgraph + Cassandra + Elasticsearch migration in #1573 , will this task still be needed, or is it now obsolete and can we close it?

**Comment by sbespalov** [comment]
@carlspring  we can close it then

**Pull request closed without merging**
