### PR TITLE
issue-808: added PythonWheelArtifactGenerator

### LINKED ISSUE #808: Implement a PythonWheelArtifactGenerator
# Task Description

We need to implement a simple Python Wheel package generator to be used during testing.

The format of the Python Wheel files is described [here](https://www.python.org/dev/peps/pep-0427/#file-contents).

The code should be located in a class called `PythonWheelArtifactGenerator` under `strongbox/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-python-wheel-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator`.

The generator must produce packages that are valid, along with all the required metadata and resource files.

A test case covering the functionality will be required.

For a reference of existing generators for other providers have a look at:
* [MavenArtifactGenerator](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/MavenArtifactGenerator.java)
* [NpmArtifactGenerator](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/NpmPackageGenerator.java)
* [NugetArtifactGenerator](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/NugetPackageGenerator.java)

# Useful Links

* [Packaging Projects](https://packaging.python.org/tutorials/packaging-projects/)

# Task Relationships

This is a sub-task of #807. It should be relatively straight-forward to implement this and you should get acquainted with the master task, before proceeding.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by Firstmol**
Fixes #808.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Kind regards,

Martin

**Comment by Firstmol** [comment]
> Hi!
> 
> Thank you for your contribution!
> 
> Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?
> 
> Kind regards,
> 
> Martin

ok

**Comment by carlspring** [comment]
This pull looks great!

I'll merge it once the Jenkins checks have passed!

**Comment by carlspring** [comment]
Thank you for your contribution, Yury and congratulations on your first pull request! :)

**Comment by carlspring** [comment]
This task relates to #1267 . It will be great to re-work the metadata generation using the writer which @timur27 will provide via his pull request.

**Pull request merged**
