### PR TITLE
Added support of license types in NPM test artifacts 

### LINKED ISSUE #1725: Make it possible to specify the license types of NPM test artifacts
# Task Description

It should be possible to specify under what license a generated test artifact is. This should be controllable via the implementation of the `org.carlspring.strongbox.testing.artifact.NpmTestArtifact` annotation and `org.carlspring.strongbox.artifact.generator.NpmArtifactGenerator`.

An artifact can have no, one, or more licenses. By default, it should not have one.

# Tasks

The following tasks will need to be carried out:

* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.NpmTestArtifact`.
  * [ ] Add a `LicenseConfiguration[] licenses() default {};` interface property. Use license contants from `org.carlspring.strongbox.testing.artifact.LicenseType`,
* [ ] Make the necessary changes to the `org.carlspring.strongbox.artifact.generator.NpmArtifactGenerator`.
  * [ ] Implement license file copying. If specified, these would be a mapping for the licenses via the `LicenseConfiguration` to where the `LICENSE.md` files from `strongbox-storage/strongbox-storage-api/src/test/resources/licenses/${license_short_name}` should be copied to (check #1723 and, especially, #1732  for more details). Figure out what the default locations for license files in NPM should be (most-probably in the root).
  * [ ] Make sure the produced `package.json` contains the list of `licenses`.
* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.NpmArtifactGeneratorStrategy`.
* [ ] Add a test illustrating:
  * [ ] An artifact with no licenses.
  * [ ] An artifact with more than one licenses.
  * [ ] An artifact with a licenses in different destination paths.

# Task Relationships

This is a sub-task of: #1723 . Check #1732 for details of how this was implemented for Maven.

# Useful Links

* [Strongbox Developer Guide: Writing Tests](https://strongbox.github.io/developer-guide/writing-tests.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

### PR DESCRIPTION
**Pull request by anki2189**
# Pull Request Description

This pull request closes #1725 

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

# Code Review And Pre-Merge Checklist

* [x] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code in hard-to-understand areas.
* [x] My changes generate no new warnings.
* [x] I have added tests that prove my fix is effective or that my feature works.
* [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by anki2189** [comment]
@carlspring Please review the changes.

**Comment by carlspring** [comment]
Hi @anki2189 ,

Thanks for this pull request!

Could you please:
* Rebase this pull request
* Add a link to the documentation of NPM where this is specified
* Add some sample output of what is currently being generated from the tests

Much appreciated!

**Comment by anki2189** [comment]
```
{
	"name": "@carlspring/npm-test-view-with-license",
	"version": "1.0.0",
	"keywords": [],
	"licenses": [{
		"type": "Apache 2.0",
		"url": "http://www.apache.org/licenses/LICENSE-2.0"
	}, {
		"type": "MIT License",
		"url": "https://opensource.org/licenses/MIT"
	}],
	"contributors": [],
	"maintainers": [],
	"files": [],
	"man": [],
	"bundledDependencies": [],
	"os": [],
	"cpu": [],
	"dist": {}
}
```


Doc. [link](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license)

**Comment by carlspring** [comment]
Thank you very much, @anki2189 ! :)

**Pull request merged**
