### PR TITLE
checkstyle - intial version of ruleset added

### PR DESCRIPTION
**Pull request by leonorader**
Issue #538 
So I added the initial version of the checkstyle ruleset. I run in on the code, and it had many warnings, then I run in on the example code on the guildelines page and it was all good.

A few more things to mention:
- it will check only Java files for now
- read more on the checks [here](http://checkstyle.sourceforge.net/checks.html)
- I set the level to warning, but later it can be changed to error if you want
- each warning will mention the name of the check that causes the violation so you can read about it
- I went though the codebase and I haven't found any real javadoc, but it could be also configured later

To be able to run a check, you can add these lines to the main pom:
```
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-checkstyle-plugin</artifactId>
            <version>3.0.0</version>
            <dependencies>
                <dependency>
                    <groupId>com.puppycrawl.tools</groupId>
                    <artifactId>checkstyle</artifactId>
                    <version>8.13</version>
                </dependency>
            </dependencies>
            <configuration>
                <configLocation>strongbox-checks.xml</configLocation>
                <consoleOutput>true</consoleOutput>
            </configuration>
        </plugin>
    </plugins>
</build>
```

And run checkstyle:check. You will see the list of warnings in the console. :)

### CODE REVIEW

**Comment by carlspring** [comment]
@leonorader,

I've had a look at the pull and it looks good (although, I haven't yet had a chance to try out myself)! One small request -- would you mind moving the `maven-checkstyle-plugin` into a Maven `<profile>` called `checkstyle`? We wouldn't want to run this upon every build. It would have to run only on our CI server, as it would otherwise slow things down significantly.

**Comment by leonorader** [comment]
sure! would you like to have this profile in the parent pom?

**Comment by carlspring** [comment]
Yeah, I think that would be the best place! Thanks! :)

**Comment by carlspring** [comment]
Hi,

Could you please sign our ICLA?

**Comment by leonorader** [comment]
Of course! :)

Anyway could you please help why Jenkins has test failures? I really don't know what I should do exactly.
2 tests failed in this file: org.carlspring.strongbox.providers.repository.MavenProxyRepositoryProviderTestIT.whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist

**Comment by carlspring** [comment]
Please, disregard these two failures.

**Pull request merged**
