### PR TITLE
Issue 1183: Dropped the /greet resource 

### LINKED ISSUE #1183: Drop the /greet resource
# Task Description

In the past, we has some tests using the `/greet` path in the layout provider controllers. We need to remove these methods from the controllers and tests.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by theomails**
Fixes #1183.

Build is successful with both the commands

`mvn clean install`

and

`mvn clean install -Dintegration.tests`

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by theomails** [comment]
Hi Martin!

Mailed you the ICLA and added me to the CONTRIBUTING.md.

Kind regards,

Theodore

**Comment by carlspring** [comment]
@theomails,

The username under which you're committing and pushing to Github seems to be mis-configured. You will have to look into how to configure your git settings properly, amend the author of the commits and then force push back to the branch. (When your user is properly set up, you see your avatar when against your commits in the commit history, otherwise it's a default grey avatar).

I will wait for these changes before merging this! Thanks! :)

**Comment by theomails** [comment]
Sorry about that!
I have now fixed the user settings for this project folder and amended the commit.

**Comment by carlspring** [comment]
Great! Thank you and congratulations on your first pull request! :)

**Pull request merged**
