### PR TITLE
issues/944: `spring-boot` version downgrade to `2.0.6-RELEASE`

### PR DESCRIPTION
**Pull request by sbespalov**

### CODE REVIEW

**Comment by sbespalov** [comment]
@steve-todorov can you check `swit` for this PR?

**Comment by steve-todorov** [comment]
Looks good to me and Jenkins :smiley:

**Comment by carlspring** [comment]
Thanks for rolling it back, @sbespalov ! :)

**Comment by carlspring** [comment]
@ptirador : We'll need to have a follow-up issue+pull request for this and investigate what's happening with Jetty (or whatever other change is responsible for this that came from the Spring Boot upgrade).

**Pull request merged**
