### PR TITLE
New change on the list files

### PR DESCRIPTION
**Pull request by IIEleniII**
@carlspring 
Following your advice i made a new fork on strongbox project.

I renamed the property, specifically in the files on the list.

The previous time i made a pull before you giving me the list.So i wanted to ask whether the list contains all the places needing change, or  you removed some of them since i had made some changes.

Thanks in advance

### CODE REVIEW

**Comment by carlspring** [comment]
Hi,

No, I haven't changed any of the files.

**Comment by IIEleniII** [comment]
Ok! Then all the files in the list have been updated.
Plus the strongbox-web-integration-tests.

**Comment by carlspring** [comment]
Great! Could you please sign the ICLA as explained in the [contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

**Comment by carlspring** [comment]
@IIEleniII ,

Could you please provide the signed ICLA, so I can merge the pull? Many thanks!

Martin

**Comment by carlspring** [comment]
@IIEleniII,

BTW, you may want to join our [chat](https://gitter.im/strongbox/strongbox).

**Comment by carlspring** [comment]
@IIEleniII ,

Any update? We can only accept pull requests for merging when the contributors have signed the ICLA.

Looking forward to your reply,

Martin

**Comment by carlspring** [comment]
@IIEleniII ,

I'm afraid I have to close this pull, as you haven't signed and sent me the ICLA. Another contributor did the task as well and they have signed my the ICLA, so I'll have to accept their pull instead.

Thanks for your efforts and I'm sorry they were in vain.

If you'd still like to contribute to the project, please have a look at:
- [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md)
- [Code of Conduct](https://github.com/strongbox/strongbox/blob/master/CODE-OF-CONDUCT.md)

Kind regards,

Martin

**Comment by carlspring** [comment]
Relates to #367.

**Pull request closed without merging**
