### PR TITLE
Issue-1860: Set parent version to build test version 1.0-issue-1860-SNAPSHOT

### LINKED ISSUE #1860: Upload commons-fileupload:commons-fileupload from 1.3.3 to 1.4
# Task Description

We need to upgrade `commons-fileupload:commons-fileupload` from `1.3.3` to `1.4`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to: #1847 , #1859 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

### PR DESCRIPTION
**Pull request by flaix**
# Pull Request Description

This pull request closes #1860

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

# Code Review And Pre-Merge Checklist

* [x] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code in hard-to-understand areas.
* [x] My changes generate no new warnings.
* [ ] I have added tests that prove my fix is effective or that my feature works.
* [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi @flaix ,

Thanks for this pull request! I have tested this and [it works](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1923/3/pipeline/). I will close this pull request and you can now revert the version of the `strongbox-parent` to `1.0-SNAPSHOT`.

Could you please sign the ICLA and sent it to me? Thanks! :)

**Comment by flaix** [comment]
Would you like a revert commit on strongbox-parent, or a force push that deletes the commit with the parent version 1.0-issue-1860-SNAPSHOT. That is, do you prefer to keep the history of having this extra step or do you want a clean history with only the dependency version change?

**Comment by carlspring** [comment]
It's up to you, really. It's not a big deal either way. I'd say keep it, but the choice is yours! :)

**Comment by flaix** [comment]
Your house, your rules. :smile: If you say keep it, we keep it.

**Comment by carlspring** [comment]
Thanks! I'm closing it, as it has passed testing.

**Pull request closed without merging**
