### PR TITLE
Reduce the janino logging

### PR DESCRIPTION
**Pull request by anki2189**
# Pull Request Description

This pull request closes #https://github.com/strongbox/strongbox/issues/1603

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by carlspring** [comment]
I thought we could just set the level in the `logback.xml` file... Is this not the case?

**Comment by steve-todorov** [comment]
@carlspring no, that won't work (not sure exactly why, but it doesn't). However, @anki2189 's changes have greatly reduced the Jenkins log size from `~50MB` to `~24MB`!

**Comment by anki2189** [comment]
> I thought we could just set the level in the `logback.xml` file... Is this not the case?

Changing log level in logback-spring.xml will not work as logback configuration gets loaded after JaninoClasses @steve-todorov Am i right?

**Comment by steve-todorov** [comment]
Yeah, that's my understanding as well at least from what I've seen. :)

**Comment by carlspring** [comment]
I see! Thank you very much and thanks for the clarification! :)

**Comment by fuss86** [comment]
Good job @anki2189 :)

**Pull request merged**
