### PR TITLE
issues/1145: MavenArtifactGenerator implements ArtifactGenerator interface

### PR DESCRIPTION
**Pull request by sbespalov**
Partial fix for #1145 
- `MavenArtifactGenerator` implements `ArtifactGenerator` interface
- `AqlControllerTest` reworked to use `TestArtifact` annotations
- `TestArtifact` annotation logic fixed

### CODE REVIEW

**Comment by sbespalov** [comment]
@carlspring @steve-todorov [strongbox-os-builds/794](https://jenkins.carlspring.org/job/strongbox/job/strongbox-os-builds/794/) is green

**Comment by sbespalov** [comment]
[strongbox-web-integration-tests-from-sources](https://jenkins.carlspring.org/job/strongbox/job/strongbox-web-integration-tests-from-sources/97/) green as well

**Comment by steve-todorov** [comment]
Great work! Thank for fixing this @sbespalov ! :)

**Comment by carlspring** [comment]
Looks good! Thanks! :)

**Pull request merged**
