### PR TITLE
Upgrade the maven-source-plugin from 2.2.1 to 3.2.1 #1875

### LINKED ISSUE #1875: Upgrade the maven-source-plugin from 2.2.1 to 3.2.1
# Task Description

We need to upgrade the `maven-source-plugin` from `2.2.1` to `3.2.1`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

### PR DESCRIPTION
**Pull request by Superbbbb**
# Pull Request Description

This pull request fixes #1875.

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [x] Yes, please see #...
  * [ ] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by steve-todorov** [comment]
@Superbbbb could you please check your git configuration? It looks like your email is not properly configured.

**Comment by Superbbbb** [comment]
@steve-todorov ,

I have set the name and email address and force push the code to the branch. Do I need to create a new pull request?

**Comment by carlspring** [comment]
No, you don't need a new pull request. 

I've triggered a complete build with all our tests in [our CI server here](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1886/5/pipeline).

**Comment by carlspring** [comment]
Closing this tet pull request, as it tested successfully in [Jenkins](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1886/5/pipeline).

Thank you very much! :)

**Pull request closed without merging**
