### PR TITLE
Distribution Environment Variables fixed

### PR DESCRIPTION
**Pull request by sbespalov**

### CODE REVIEW

**Comment by carlspring** [comment]
I'm not I get the goal of this pull request. Are you proposing we replace these variables with system environment ones?

**Comment by steve-todorov** [comment]
@carlspring system environment variables are not working anymore after we have migrated to Spring Boot. Most of our `strongbox-distribution.sh` options are not working right now (i.e. debug logging does not get triggered) :)

**Comment by sbespalov** [comment]
@carlspring

> I'm not sure I get the goal of this pull request. Are you proposing we replace these variables with system environment ones?

actually it already was like this, but someone dropped it during Spring Boot migration

**Comment by sbespalov** [comment]
@carlspring

> I'm not sure I get the goal of this pull request. Are you proposing we replace these variables with system environment ones?

actually it already was like this, but someone dropped it during Spring Boot migration

**Comment by sbespalov** [comment]
@carlspring

> I'm not sure I get the goal of this pull request. Are you proposing we replace these variables with system environment ones?

actually it already was like this, but someone dropped it during Spring Boot migration

**Comment by carlspring** [comment]
Thanks, Sergey! :)

**Pull request merged**
