### PR TITLE
Add a Stackoverflow badge #1507 | Added stackoverflow badge

### PR DESCRIPTION
**Pull request by priyamm**
# Pull Request Description

This pull request closes #

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by priyamm** [comment]
PR for Issue #1507

**Comment by carlspring** [comment]
Could you please change the colour to Stackoverflow's orange? Also, is it possible to change the text from `PROFILE` to `ask`, or is this not customizable?

**Comment by priyamm** [comment]
@carlspring both are customisable.

**Comment by carlspring** [comment]
If you could change these two, that'll be great!

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Pull request merged**
