### PR TITLE
Issue 1027: Rename the strongbox.config.xml property to strongbox.config

### LINKED ISSUE #1027: Rename the strongbox.config.xml property to strongbox.config
# Task Description

As we'll be migrating to YAML soon, it would be a good idea to rename the `strongbox.config.xml` property to `strongbox.config`. This is also applicable for `AuthenticationResourceManager.PROPERTY_AUTHENTICATION_PROVIDERS_LOCATION`.

This task relates to #965.

# Help

* [Our chat](https://chat.carlspring.org/)

### PR DESCRIPTION
**Pull request by adavid9**
There was a request as well we'll be migrating to YAML soon, to change the properties name.

Fixes #1027.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel on Gitter](https://gitter.im/strongbox/strongbox), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by carlspring** [comment]
I've reviewed, the pull request and it looks good, thank you! :)

**Comment by adavid9** [comment]
@carlspring This fix is ready for merge.

**Comment by carlspring** [comment]
@adavid9 ,

Could you please sync this  brnach and sort out the merge conflicts? Thanks! :)

**Comment by carlspring** [comment]
@steve-todorov ,

Would you mind running a quick test of the `strongbox-web-core` and `strongbox-distribution`for this?

**Comment by steve-todorov** [comment]
Thanks for your work on this @adavid9! :)

**Pull request merged**
