### PR TITLE
issues/1120 Upgrade OrientDB dependencies to 3.0.21

### PR DESCRIPTION
**Pull request by fuss86**

### CODE REVIEW

**Comment by fuss86** [comment]
Fixes for https://github.com/strongbox/strongbox/issues/1120

**Comment by fuss86** [comment]
https://github.com/orientechnologies/orientdb/issues/8947

**Comment by carlspring** [comment]
@fuss86 : What's the status of this task?

**Comment by fuss86** [comment]
I think we can't upgrade until orientDb guys will solve https://github.com/orientechnologies/orientdb/issues/8947 :(

**Comment by carlspring** [comment]
Closing.

**Pull request closed without merging**
