### PR TITLE
Require proper roles/privileges to access LoggingManagementController endpoints

### LINKED ISSUE #569: Require proper roles/privileges to access LoggingManagementController endpoints
Our `org.carlspring.strongbox.controllers.LoggingManagementController` currently is not properly secured. It needs to have `@PreAuthorize` for each method. The list of privileges can be found in `org.carlspring.strongbox.users.domain.Privileges`.

```
CONFIGURATION_ADD_LOGGER
CONFIGURATION_UPDATE_LOGGER
CONFIGURATION_DELETE_LOGGER
CONFIGURATION_RETRIEVE_LOG
CONFIGURATION_RETRIEVE_LOGBACK_CFG
CONFIGURATION_UPLOAD_LOGBACK_CFG
VIEW_LOGS
CONFIGURE_LOGS
```

### PR DESCRIPTION
**Pull request by adityasrini**
Fixes #569

Appends `LoggingManagementController` to have required authorities to access them.
Appends `LoggingManagementControllerTestIT` methods to test for authorities.
Fixes `pom.xml` `logging.dir` variable to point to `strongbox-vault`

### CODE REVIEW

**Comment by carlspring** [comment]
@steve-todorov : Would you mind testing this?

**Comment by adityasrini** [comment]
This is weird: `https://dev.carlspring.org/jenkins/blue/organizations/jenkins/strongbox%2Fstrongbox/detail/PR-613/1/tests`

It's still looking in the wrong directory for the log files.

**Comment by steve-todorov** [comment]
@adityasrini yes, because you haven't yet committed the fix for the `logging.dir` property ([link](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/pom.xml#L84)).

**Comment by adityasrini** [comment]
Whoops! My bad! I will update this in a commit.

**Comment by adityasrini** [comment]
@steve-todorov I did in this commit though! See this [line](https://github.com/strongbox/strongbox/pull/613/files#diff-2279de604ee480ce8236aef0f7346529R84) in the commit.

**Comment by steve-todorov** [comment]
@adityasrini good job on fixing this! :) 

@carlspring I believe this is now finished and we can merge it.

**Comment by carlspring** [comment]
Thanks for looking into this! :)

**Pull request merged**
