### PR TITLE
Testing jenkins pull request.

### PR DESCRIPTION
**Pull request by steve-todorov**
This is a testing pull request to help resolve some issues with the jenkins PR plugin. Should not be merged in the master!

### CODE REVIEW

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot ok to test

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by steve-todorov** [comment]
@cs-devops-bot rebuild

**Comment by carlspring** [comment]
@steve-todorov : Should we close this now?

**Comment by steve-todorov** [comment]
@carlspring let's leave it for a few days in case I need to test anything more.

**Pull request closed without merging**
