### PR TITLE
Issue 1856: Upgrade awaitility dependencies from 3.1.2 to 4.0.3

### LINKED ISSUE #1856: Upgrade our awaitility dependencies from 3.1.2 to 4.0.3
# Task Description

We need to upgrade `awaitility dependencies from `3.1.2` to `4.0.3`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to: #1852 , #1853 , #1854 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

### PR DESCRIPTION
**Pull request by kosuruvarunkumar**
# Pull Request Description

This pull request closes #1856 

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by kosuruvarunkumar** [comment]
@carlspring few tests were skipped, how do we address this?
Thanks

**Comment by kosuruvarunkumar** [comment]
@steve-todorov Thanks for initiating the full pipeline. All checks have passed. Do we have anything more to do to get this PR approved? 🤔 
Thank you

**Comment by steve-todorov** [comment]
Hi @kosuruvarunkumar ,

Thank you for your contribution!

Yes, you would need to signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page. We would not be able to merge your pull request otherwise.

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,
Steve

// cc @carlspring

**Comment by kosuruvarunkumar** [comment]
Thanks, @steve-todorov  for the info, I mailed the signed ICLA

**Comment by kosuruvarunkumar** [comment]
@carlspring as you acknowledged that you received the ICLA, can we have the label removed.
Thanks

**Comment by carlspring** [comment]
Closing after [successful testing](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1894/3/pipeline).

**Pull request closed without merging**
