### PR TITLE
SB-1360 pattern for storageId and repositoryId

### PR DESCRIPTION
**Pull request by fuss86**

### CODE REVIEW

**Comment by fuss86** [comment]
ready :) @steve-todorov

**Comment by carlspring** [comment]
Could you please update the wiki page to mention these rules? Thanks!

**Comment by fuss86** [comment]
https://strongbox.github.io/knowledge-base/storages/ and https://strongbox.github.io/knowledge-base/repositories/ return 404 for the time being.

**Comment by fuss86** [comment]
https://github.com/strongbox/strongbox-docs/pull/6/files

**Pull request merged**
